Add missing `exc` exception variable for qa/bin/functional
  File "./exabgp/./qa/bin/functional", line 155, in collect
    self.message = str(exc)
UnboundLocalError: local variable 'exc' referenced before assignment

Signed-off-by: Donatas Abraitis <donatas@opensourcerouting.org>